(define (problem control-meeting)
  (:domain smart-office)
  (:objects plugwise1 plugwise2 plugwise3 - device meeting1 - room)
  (:init
    (room meeting1)
    (light plugwise1)
    (conditioner plugwise2)
    (dehumidifier plugwise3)
    (installed-in-light plugwise1 meeting1)
    (installed-in-conditioner plugwise2 meeting1)
    (installed-in-dehumidifier plugwise3 meeting1)
    (light-on plugwise1)
    (conditioner-on plugwise2)
    (dehumidifier-off plugwise3)
  )
  (:goal
    (and
      (light-off plugwise1)
      (conditioner-off plugwise2)
      (dehumidifier-off plugwise3)
     )
  )
)
